# Generated by Django 6.1.1 on 2026-09-14 16:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("prefix", models.CharField(max_length=255, unique=True)),
                ("hash", models.CharField(max_length=255, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rate_limit_per_minute", models.IntegerField(default=100)),
                ("monthly_budget_micro_cents", models.IntegerField(default=500000000)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("requested_model", models.CharField(max_length=255)),
                ("used_model", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("prompt_tokens", models.IntegerField(null=True)),
                ("completion_tokens", models.IntegerField(null=True)),
                ("cost_micro_cents", models.IntegerField(null=True)),
                ("gateway_latency_ms", models.IntegerField(null=True)),
                ("provider_latency_ms", models.IntegerField(null=True)),
                ("status_code", models.IntegerField()),
                ("error_code", models.CharField(max_length=255)),
                ("cache_hit", models.BooleanField(default=False)),
                ("streaming", models.BooleanField(default=False)),
                ("fallback_depth", models.IntegerField(default=0)),
                (
                    "request_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keys.apikey"
                    ),
                ),
            ],
        ),
    ]
